### ISSUE TITLE
Statemine collator v5.3.0 node crash

### ISSUE THREAD

**Issue by paulormart** [paritytech/cumulus#1157]
Statemine collator node recently upgraded to v5.3.0  from v5.2.0 crashes with the following error:

[statemine.log](https://github.com/paritytech/cumulus/files/8451347/statemine.log)

```
Apr 08 09:07:00 localhost polkadot-collator[156999]: 2022-04-08 09:07:00 [Parachain] ⚙️  Syncing  0.0 bps, target=#1932231 (4 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 93.1kiB/s ⬆ 1.6kiB/s
Apr 08 09:07:01 localhost polkadot-collator[156999]: 2022-04-08 09:07:01 [Relaychain] 💤 Idle (15 peers), best: #12161402 (0x50b2…9817), finalized #12161398 (0x5f9e…77d3), ⬇ 149.3kiB/s ⬆ 192.7kiB/s
Apr 08 09:07:03 localhost polkadot-collator[156999]: 2022-04-08 09:07:03 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488:9
Apr 08 09:07:03 localhost polkadot-collator[156999]: 2022-04-08 09:07:03 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 09:07:03 localhost polkadot-collator[156999]: WASM backtrace:
Apr 08 09:07:03 localhost polkadot-collator[156999]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 09:07:03 localhost polkadot-collator[156999]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 09:07:03 localhost polkadot-collator[156999]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 09:07:03 localhost polkadot-collator[156999]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 09:07:03 localhost polkadot-collator[156999]:     
Apr 08 09:07:03 localhost polkadot-collator[156999]: 2022-04-08 09:07:03 [Parachain] 💔 Error importing block 0xe0ac9869bc41d54ec70d13c9bb5e51a939d8093d3f5cad50138cb08ec8469d72: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 09:07:03 localhost polkadot-collator[156999]: WASM backtrace:
Apr 08 09:07:03 localhost polkadot-collator[156999]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 09:07:03 localhost polkadot-collator[156999]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 09:07:03 localhost polkadot-collator[156999]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 09:07:03 localhost polkadot-collator[156999]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 09:07:03 localhost polkadot-collator[156999]:     
Apr 08 09:07:05 localhost polkadot-collator[156999]: 2022-04-08 09:07:05 [Parachain] ⚙️  Syncing  0.0 bps, target=#1932231 (4 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 96.1kiB/s ⬆ 0.7kiB/s
Apr 08 09:07:06 localhost polkadot-collator[156999]: 2022-04-08 09:07:06 [Relaychain] 💤 Idle (18 peers), best: #12161402 (0x50b2…9817), finalized #12161399 (0xd33b…592e), ⬇ 340.9kiB/s ⬆ 99.9kiB/s
Apr 08 09:07:06 localhost polkadot-collator[156999]: 2022-04-08 09:07:06 [Relaychain] ✨ Imported #12161403 (0x2d7a…a272)
```

**Comment by paradox-tt** [comment]
We also encountered a similar occurrence;  after the error blocks don't sync further.

```
Apr 08 12:16:06 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:06 [Relaychain] ✨ Imported #12163289 (0x941a…8cb7)
Apr 08 12:16:06 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:06 [Relaychain] ✨ Imported #12163289 (0xc41d…21ae)
Apr 08 12:16:06 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:06 [Relaychain] ✨ Imported #12163289 (0xade7…385b)
Apr 08 12:16:06 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:06 [Relaychain] ✨ Imported #12163289 (0xfaae…6969)
Apr 08 12:16:10 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:10 [Relaychain] 💤 Idle (26 peers), best: #12163289 (0x941a…8cb7), finalized #12163285 (0xb558…759c), ⬇ 654.2kiB/s ⬆ 581.3kiB/s
Apr 08 12:16:10 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:10 [Parachain] ⚙️  Syncing  0.0 bps, target=#1932648 (3 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 44.6kiB/s ⬆ 1.8kiB/s
Apr 08 12:16:12 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:12 [Relaychain] ✨ Imported #12163290 (0x0c68…fe69)
Apr 08 12:16:12 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:12 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488:9
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:12 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]: WASM backtrace:
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:12 [Parachain] 💔 Error importing block 0xe0ac9869bc41d54ec70d13c9bb5e51a939d8093d3f5cad50138cb08ec8469d72: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachab>
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]: WASM backtrace:
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 12:16:13 ns3210020 polkadot-collator[3390706]:
Apr 08 12:16:15 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:15 [Relaychain] 💤 Idle (26 peers), best: #12163290 (0x0c68…fe69), finalized #12163286 (0x53fe…545d), ⬇ 1.3MiB/s ⬆ 429.1kiB/s
Apr 08 12:16:15 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:15 [Parachain] ⚙️  Syncing  0.0 bps, target=#1932648 (3 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 34.3kiB/s ⬆ 1.1kiB/s
Apr 08 12:16:18 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:18 [Relaychain] ✨ Imported #12163291 (0x70cf…286d)
Apr 08 12:16:20 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:20 [Relaychain] 💤 Idle (25 peers), best: #12163291 (0x70cf…286d), finalized #12163286 (0x53fe…545d), ⬇ 433.5kiB/s ⬆ 914.5kiB/s
Apr 08 12:16:20 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:20 [Parachain] ⚙️  Syncing  0.0 bps, target=#1932648 (3 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 52.3kiB/s ⬆ 1.0kiB/s
Apr 08 12:16:24 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:24 [Relaychain] ✨ Imported #12163292 (0x6353…4b46)
Apr 08 12:16:25 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:25 [Relaychain] 💤 Idle (25 peers), best: #12163292 (0x6353…4b46), finalized #12163289 (0x941a…8cb7), ⬇ 531.2kiB/s ⬆ 487.1kiB/s
Apr 08 12:16:25 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:25 [Parachain] ⚙️  Syncing  0.0 bps, target=#1932648 (3 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 161.2kiB/s ⬆ 2.4kiB/s
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:30 [Relaychain] ✨ Imported #12163293 (0x4af4…501d)
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:30 [Relaychain] 💤 Idle (25 peers), best: #12163293 (0x4af4…501d), finalized #12163290 (0x0c68…fe69), ⬇ 541.8kiB/s ⬆ 761.8kiB/s
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:30 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488:9
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:30 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: WASM backtrace:
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:30 [Parachain] 💔 Error importing block 0xe0ac9869bc41d54ec70d13c9bb5e51a939d8093d3f5cad50138cb08ec8469d72: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachab>
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: WASM backtrace:
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]:
Apr 08 12:16:30 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:30 [Parachain] ⚙️  Syncing  0.0 bps, target=#1932648 (3 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 63.5kiB/s ⬆ 2.1kiB/s
Apr 08 12:16:35 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:35 [Relaychain] 💤 Idle (25 peers), best: #12163293 (0x4af4…501d), finalized #12163290 (0x0c68…fe69), ⬇ 234.6kiB/s ⬆ 424.3kiB/s
Apr 08 12:16:35 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:35 [Parachain] 💤 Idle (2 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 77.0kiB/s ⬆ 0.3kiB/s
Apr 08 12:16:36 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:36 [Relaychain] ✨ Imported #12163294 (0xa058…519e)
Apr 08 12:16:40 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:40 [Relaychain] 💤 Idle (24 peers), best: #12163294 (0xa058…519e), finalized #12163290 (0x0c68…fe69), ⬇ 277.0kiB/s ⬆ 454.0kiB/s
Apr 08 12:16:40 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:40 [Parachain] 💤 Idle (2 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 1.8kiB/s ⬆ 1.9kiB/s
Apr 08 12:16:42 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:42 [Relaychain] ✨ Imported #12163295 (0x40da…cd0d)
Apr 08 12:16:45 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:45 [Relaychain] 💤 Idle (23 peers), best: #12163295 (0x40da…cd0d), finalized #12163291 (0x70cf…286d), ⬇ 274.5kiB/s ⬆ 684.9kiB/s
Apr 08 12:16:45 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:45 [Parachain] 💤 Idle (2 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 0.8kiB/s ⬆ 0.8kiB/s
Apr 08 12:16:48 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:48 [Relaychain] ✨ Imported #12163296 (0x0ca6…6f5a)
Apr 08 12:16:50 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:50 [Relaychain] 💤 Idle (23 peers), best: #12163296 (0x0ca6…6f5a), finalized #12163293 (0x4af4…501d), ⬇ 599.1kiB/s ⬆ 794.7kiB/s
Apr 08 12:16:50 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:50 [Parachain] 💤 Idle (2 peers), best: #1931776 (0xfb28…ede7), finalized #1931776 (0xfb28…ede7), ⬇ 1.7kiB/s ⬆ 2.0kiB/s
Apr 08 12:16:54 ns3210020 polkadot-collator[3390706]: 2022-04-08 12:16:54 [Relaychain] ✨ Imported #12163297 (0x02a5…f5b5)

```

**Comment by Curu24** [comment]
we had the similar issue
`Apr 08 05:11:18 statemine polkadot[435830]: 2022-04-08 05:11:18 [Relaychain] ✨ Imported #12159048 (0x33a4…c089)
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488:9
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 05:11:19 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:19 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:19 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:19 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:19 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:19 statemine polkadot[435830]:     
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] 💔 Error importing block 0x1ebd49758edd404d8dbbd7b1306ec8aac0d526633a0070f14cca4685370e212a: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable>
Apr 08 05:11:19 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:19 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:19 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:19 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:19 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:19 statemine polkadot[435830]:     
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] ⚙️  Syncing  0.0 bps, target=#1931831 (2 peers), best: #1925570 (0xf16f…6958), finalized #1925569 (0x055d…295a), ⬇ 97.0kiB/s ⬆ 10.7kiB/s
Apr 08 05:11:21 statemine polkadot[435830]: 2022-04-08 05:11:21 [Relaychain] 💤 Idle (19 peers), best: #12159048 (0x33a4…c089), finalized #12159044 (0x6feb…2879), ⬇ 178.7kiB/s ⬆ 423.7kiB/s
Apr 08 05:11:23 statemine polkadot[435830]: 2022-04-08 05:11:23 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488:9
Apr 08 05:11:23 statemine polkadot[435830]: 2022-04-08 05:11:23 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 05:11:23 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:23 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:23 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:23 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:23 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:23 statemine polkadot[435830]:     
Apr 08 05:11:23 statemine polkadot[435830]: 2022-04-08 05:11:23 [Parachain] 💔 Error importing block 0x1ebd49758edd404d8dbbd7b1306ec8aac0d526633a0070f14cca4685370e212a: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable>
Apr 08 05:11:23 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:23 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:23 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:23 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:23 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:23 statemine polkadot[435830]:     
Apr 08 05:11:24 statemine polkadot[435830]: 2022-04-08 05:11:24 [Relaychain] ✨ Imported #12159049 (0xa6b8…3971)
`

**Comment by Curu24** [comment]
we had a similar issue
```
Apr 08 05:11:18 statemine polkadot[435830]: 2022-04-08 05:11:18 [Relaychain] ✨ Imported #12159048 (0x33a4…c089)
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488:9
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 05:11:19 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:19 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:19 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:19 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:19 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:19 statemine polkadot[435830]:     
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] 💔 Error importing block 0x1ebd49758edd404d8dbbd7b1306ec8aac0d526633a0070f14cca4685370e212a: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable>
Apr 08 05:11:19 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:19 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:19 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:19 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:19 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:19 statemine polkadot[435830]:     
Apr 08 05:11:19 statemine polkadot[435830]: 2022-04-08 05:11:19 [Parachain] ⚙️  Syncing  0.0 bps, target=#1931831 (2 peers), best: #1925570 (0xf16f…6958), finalized #1925569 (0x055d…295a), ⬇ 97.0kiB/s ⬆ 10.7kiB/s
Apr 08 05:11:21 statemine polkadot[435830]: 2022-04-08 05:11:21 [Relaychain] 💤 Idle (19 peers), best: #12159048 (0x33a4…c089), finalized #12159044 (0x6feb…2879), ⬇ 178.7kiB/s ⬆ 423.7kiB/s
Apr 08 05:11:23 statemine polkadot[435830]: 2022-04-08 05:11:23 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/executive/src/lib.rs:488:9
Apr 08 05:11:23 statemine polkadot[435830]: 2022-04-08 05:11:23 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Apr 08 05:11:23 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:23 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:23 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:23 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:23 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:23 statemine polkadot[435830]:     
Apr 08 05:11:23 statemine polkadot[435830]: 2022-04-08 05:11:23 [Parachain] 💔 Error importing block 0x1ebd49758edd404d8dbbd7b1306ec8aac0d526633a0070f14cca4685370e212a: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable>
Apr 08 05:11:23 statemine polkadot[435830]: WASM backtrace:
Apr 08 05:11:23 statemine polkadot[435830]:     0: 0x22dc - <unknown>!rust_begin_unwind
Apr 08 05:11:23 statemine polkadot[435830]:     1: 0x1fbf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349
Apr 08 05:11:23 statemine polkadot[435830]:     2: 0x11286a - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h53ef3e2470734592
Apr 08 05:11:23 statemine polkadot[435830]:     3: 0x163a26 - <unknown>!Core_execute_block
Apr 08 05:11:23 statemine polkadot[435830]:     
Apr 08 05:11:24 statemine polkadot[435830]: 2022-04-08 05:11:24 [Relaychain] ✨ Imported #12159049 (0xa6b8…3971)
```

**Comment by bkchr** [comment]
Do all of you run with `--state-cache-size 0`?

**Comment by Curu24** [comment]
> Do all of you run with `--state-cache-size 0`?

no, but we added this after the crash as it often helped on other parachains. but wasn't sure if I should recommend to others as well

**Comment by bkchr** [comment]
Yes currently is is required for all.

**Comment by Curu24** [comment]
ok, for Polkadotters flag added.
are there actually any other recommendations? or list of preferred flags?

**Comment by bkchr** [comment]
That's it for now :D

**Comment by paradox-tt** [comment]
Added on this end as well and recommending to the others.

**Comment by paulormart** [comment]
Ok, i was not aware of that flag,  just added as well.
