### ISSUE TITLE
Can not Produce Block on Rococo

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/cumulus#1176]
After https://github.com/paritytech/subport/issues/341, we can not produce any block. (I have cleaned DB.)
I also test the new chain spec on rococo-local. And it works well.
So I think there are some issues on relay chain side. 

How did you reset the parachain chain?
We hope to keep the old ParaId. So, do you need to purge some old data on relay chain side?

Here are some logs:

```
Apr 18 02:06:54 pangolin-g1 darwinia-collator[1474826]: 2022-04-18 02:06:54 [Parachain] panicked at 'assertion failed: `(left == right)`
Apr 18 02:06:54 pangolin-g1 darwinia-collator[1474826]:   left: `0x0000000000000000000000000000000000000000000000000000000000000000`,
Apr 18 02:06:54 pangolin-g1 darwinia-collator[1474826]:  right: `0xda16040cee3e0c7071aadb712d56bc43a1f24de9501f5eff8dbea1ec42d5bca1`', /root/.cargo/git/checkouts/cumulus-59522f43471fa161/86f76c5/pallets/parachain-system/src/lib.rs:764:9
Apr 18 02:06:54 pangolin-g1 darwinia-collator[1474826]: 2022-04-18 02:06:54 [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Other("Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\nwasm backtrace:\n    0: 0x4a8f - <unknown>!rust_begin_unwind\n    1: 0x22fe - <unknown>!core::panicking::panic_fmt::h8f11323637b4db3b\n    2: 0x5395 - <unknown>!core::panicking::assert_failed_inner::hb7fa033f7ee539c7\n    3: 0x142f11 - <unknown>!core::panicking::assert_failed::h326365a8eb2b7404\n    4: 0x95564 - <unknown>!<pangolin_parachain_runtime::Call as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::hcd2d17ee77c4c463\n    5: 0x7aefd - <unknown>!<pangolin_parachain_runtime::Call as sp_runtime::traits::Dispatchable>::dispatch::hdeec241f7c6100f0\n    6: 0x2356ba - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h13c7737a816f2dfb\n    7: 0x23e917 - <unknown>!BlockBuilder_apply_extrinsic\n"). Dropping.
Apr 18 02:06:54 pangolin-g1 darwinia-collator[1474826]: 2022-04-18 02:06:54 [Parachain] panicked at 'set_validation_data inherent needs to be present in every block!', /root/.cargo/git/checkouts/cumulus-59522f43471fa161/86f76c5/pallets/parachain-system/src/lib.rs:144:13
Apr 18 02:06:54 pangolin-g1 darwinia-collator[1474826]: 2022-04-18 02:06:54 [Parachain] Proposing failed: ClientImport("RuntimeApiError(Application(Execution(Other(\"Wasm execution trapped: wasm trap: wasm `unreachable` instruction executed\\nwasm backtrace:\\n    0: 0x4a8f - <unknown>!rust_begin_unwind\\n    1: 0x22fe - <unknown>!core::panicking::panic_fmt::h8f11323637b4db3b\\n    2: 0x4cf0d - <unknown>!<(TupleElement0,TupleElement1) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::h84c47e59916116ef\\n    3: 0x23ed75 - <unknown>!BlockBuilder_finalize_block\\n\"))))")
```

I'm not sure if this is a bug.
I'm on polkadot-v0.9.16.

[pallets/parachain-system/src/lib.rs:764:9](https://github.com/paritytech/cumulus/blob/polkadot-v0.9.16/pallets/parachain-system/src/lib.rs#L759-L764)
[pallets/parachain-system/src/lib.rs:144:13](https://github.com/paritytech/cumulus/blob/polkadot-v0.9.16/pallets/parachain-system/src/lib.rs#L144-L147)

Looking forward to the response!
Thanks!

**Comment by al3mart** [comment]
Let me double check that everything is in place.
I will start by cleaning your state at the relaychain and setting it up again for you.

After that a fresh start of the collators from your side would be needed, this means resyncing. I would let you know then.

**Comment by bkchr** [comment]
@AurevoirXavier please post a link to the code. ty.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier please post a link to the code. ty.

You mean our parachain code?
https://github.com/darwinia-network/darwinia-parachain

**Comment by bkchr** [comment]
It looks like the inherent is not build, I don't really see why. However, I also don't really understand why you copied all this code for having a shell runtime on your client side. You could probably remove all this code?

**Comment by AurevoirXavier** [comment]
> It looks like the inherent is not build, I don't really see why. However, I also don't really understand why you copied all this code for having a shell runtime on your client side. You could probably remove all this code?

Sorry, I didn't get it.
What code should I remove?

**Comment by al3mart** [comment]
I am onboarding you as a parachain now, aprox 50' from now. Please, run your collators from scratch.

**Comment by AurevoirXavier** [comment]
Works good now.

**Comment by bkchr** [comment]
@AurevoirXavier and what was it?

**Comment by N1ghtStorm** [comment]
It looks like I face the same issue on Sora Parachain (ParaId 2011)

```
    
2023-04-03 19:53:18.491  INFO tokio-runtime-worker substrate: [Relaychain] ✨ Imported #4799408 (0x3621…2d35)    
2023-04-03 19:53:18.491 TRACE tokio-runtime-worker parachain::collator-protocol: [Relaychain] Own view change view=OurView { view: View { heads: [0x36219bf01b87bfde26cff986e72a2dd977b29c3fddd93ca919933d7890d02d35, 0x499f75e2bc161713b3479de9f6a9e7a636f2388236d7e7484de5163cec26bf9e], finalized_number: 4799405 }, span_per_head: {0x499f75e2bc161713b3479de9f6a9e7a636f2388236d7e7484de5163cec26bf9e: <jaeger span>, 0x36219bf01b87bfde26cff986e72a2dd977b29c3fddd93ca919933d7890d02d35: <jaeger span>} }
2023-04-03 19:53:18.532  INFO tokio-runtime-worker cumulus-collator: [Parachain] Starting collation. relay_parent=0x36219bf01b87bfde26cff986e72a2dd977b29c3fddd93ca919933d7890d02d35 at=0x8685a8d3e57fa8024b91b8ead6cc97acf953889c6fb0a355602826a1e2db198f
2023-04-03 19:53:18.535  INFO tokio-runtime-worker sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent 0x8685a8d3e57fa8024b91b8ead6cc97acf953889c6fb0a355602826a1e2db198f    
2023-04-03 19:53:18.539 ERROR tokio-runtime-worker runtime: [Parachain] panicked at 'assertion failed: `(left == right)`
  left: `0x0000000000000000000000000000000000000000000000000000000000000000`,
 right: `0x3c5b82dbc87c647a5b6f37b9fbdfcf839752c05f6bec5dfecf8c94e0a3419030`', /Users/dmitry/.cargo/git/checkouts/cumulus-59522f43471fa161/fb8c5a3/pallets/parachain-system/src/lib.rs:837:9    
2023-04-03 19:53:18.542  WARN tokio-runtime-worker sp_state_machine::overlayed_changes::changeset: [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.    
2023-04-03 19:53:18.542  WARN tokio-runtime-worker sp_state_machine::overlayed_changes::changeset: [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.    
2023-04-03 19:53:18.543  WARN tokio-runtime-worker sc_basic_authorship::basic_authorship: [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x23fe97 - <unknown>!rust_begin_unwind
    1: 0x9750 - <unknown>!core::panicking::panic_fmt::h682ca3a56f4131fa
    2: 0x997c - <unknown>!core::panicking::assert_failed_inner::h53871b170d71d96d
    3: 0xab1fd - <unknown>!core::panicking::assert_failed::h8608728d0f15aa17
    4: 0x1cafde - <unknown>!cumulus_pallet_parachain_system::<impl cumulus_pallet_parachain_system::pallet::Pallet<T>>::process_inbound_downward_messages::h92aaeb90f2c5421c
    5: 0x10d1d7 - <unknown>!frame_support::storage::transactional::with_storage_layer::hdaac31fd9f6f500e
    6: 0x1b7da5 - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h662f877d9d549b2d
    7: 0x4eeec - <unknown>!<parachain_template_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::hcd0cdda00f67b2df
    8: 0x4d1e2 - <unknown>!<parachain_template_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::hef62d72e3a0ea69e
    9: 0xb08e4 - <unknown>!<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::h13c7ee62f138be1a
   10: 0x1f40f1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::ha44189ce057b4776
   11: 0x20daa0 - <unknown>!BlockBuilder_apply_extrinsic
. Dropping.    
2023-04-03 19:53:18.543 ERROR tokio-runtime-worker runtime: [Parachain] panicked at 'set_validation_data inherent needs to be present in every block!', /Users/dmitry/.cargo/git/checkouts/cumulus-59522f43471fa161/fb8c5a3/pallets/parachain-system/src/lib.rs:191:13    
2023-04-03 19:53:18.544  WARN tokio-runtime-worker aura: [Parachain] Proposing failed: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:


```
