### ISSUE TITLE
Tests in the `master` branch are broken

### ISSUE THREAD

**Issue by alvicsam** [paritytech/cumulus#1520]
https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/1728689

test name: `polkadot-parachain::polkadot_argument_parsing polkadot_argument_parsing`

<details><summary>Logs</summary>

```bash
--- STDOUT:                                        polkadot-parachain::polkadot_argument_parsing polkadot_argument_parsing ---
running 1 test
test polkadot_argument_parsing ... FAILED
failures:
failures:
    polkadot_argument_parsing
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 21.03s
--- STDERR:                                        polkadot-parachain::polkadot_argument_parsing polkadot_argument_parsing ---
2022-08-09 07:27:36 Polkadot parachain    
2022-08-09 07:27:36 ✌️  version 0.9.230-ed57c8aca96    
2022-08-09 07:27:36 ❤️  by Parity Technologies <admin@parity.io>, 2017-2022    
2022-08-09 07:27:36 📋 Chain specification: Local Testnet    
2022-08-09 07:27:36 🏷  Node name: foolish-oatmeal-0384    
2022-08-09 07:27:36 👤 Role: FULL    
2022-08-09 07:27:36 💾 Database: RocksDb at polkadot_argument_parsing/chains/local_testnet/db/full    
2022-08-09 07:27:36 ⛓  Native runtime: test-parachain-9230 (test-parachain-0.tx1.au1)    
2022-08-09 07:27:38 Running in --dev mode, RPC CORS has been disabled.    
2022-08-09 07:27:38 Parachain id: Id(1000)    
2022-08-09 07:27:38 Parachain Account: 5Ec4AhPZk8STuex8Wsi9TwDtJQxKqzPJRCH7348Xtcs9vZLJ    
2022-08-09 07:27:38 Parachain genesis state: 0x0000000000000000000000000000000000000000000000000000000000000000009b2a97568aa5bdad4c8204f44a150951fbea02000d76de717094fb804d64bf0303170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400    
2022-08-09 07:27:38 Is collating: no    
2022-08-09 07:27:43 [Parachain] 🔨 Initializing Genesis block/state (state: 0x9b2a…bf03, header-hash: 0x4bf5…471b)    
2022-08-09 07:27:46 [Relaychain] [0] 💸 generated 1 npos voters, 1 from validators and 0 nominators    
2022-08-09 07:27:46 [Relaychain] Took active validators from set with wrong size    
2022-08-09 07:27:46 [Relaychain] Took active validators from set with wrong size    
2022-08-09 07:27:46 [Relaychain] Took active validators from set with wrong size.    
2022-08-09 07:27:46 [Relaychain] Took active validators from set with wrong size    
2022-08-09 07:27:52 [Relaychain] 🔨 Initializing Genesis block/state (state: 0x6f53…20c7, header-hash: 0x7351…c05e)    
2022-08-09 07:27:52 [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2022-08-09 07:27:55 [Relaychain] 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2022-08-09 07:27:55 [Relaychain] 🏷  Local node identity is: 12D3KooWCreoVqfCu4UAzDKd4r546Cp2D9VkYasrs15FwqTLdi8S    
2022-08-09 07:27:55 [Relaychain] Can't listen on /ip6/::/tcp/30334 because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(B(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))))))) })    
2022-08-09 07:27:55 [Relaychain] Can't listen on /ip4/0.0.0.0/tcp/30334 because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(B(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))))))) })    
thread 'polkadot_argument_parsing' panicked at 'assertion failed: `(left == right)`
  left: `Some(false)`,
 right: `Some(true)`: the process must exit gracefully after signal SIGINT', polkadot-parachain/tests/polkadot_argument_parsing.rs:53:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: polkadot_argument_parsing::polkadot_argument_parsing::run_command_and_kill
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
   Canceling due to test failure: 8 tests still running
```

</details>

**Comment by bkontur** [comment]
@alvicsam 
yes, I saw that also in my PR, I will investigate later

**Comment by bkchr** [comment]
This is just some flaky test, because we have a timeout that is too short.

We need to copy the following [function](https://github.com/paritytech/substrate/blob/8e600ee0515122667cd091d632104708d343ca34/bin/node/cli/tests/common.rs#L87) and start using it in these tests here.
