### ISSUE TITLE
Panic when running archive node

### ISSUE THREAD

**Issue by TorstenStueber** [paritytech/cumulus#1620]
When trying to run an archive node and sync it with our collator nodes, they will always panic with the following error message. For that reason we are not able to successfully run our archive nodes.

```
====================

Version: 0.1.0-47ee9f424b5

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/f6f9d5e73d5524b6281c10a5c89b7db35c330634/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: <quicksink::SinkImpl<S,F,T,A,E> as futures_sink::Sink<A>>::poll_flush
   6: <libp2p_websocket::framed::Connection<T> as futures_sink::Sink<libp2p_websocket::framed::OutgoingData>>::poll_flush
   7: <libp2p_noise::io::NoiseOutput<T> as futures_io::if_std::AsyncWrite>::poll_flush
   8: multistream_select::negotiated::Negotiated<TInner>::poll
   9: <multistream_select::negotiated::Negotiated<TInner> as futures_io::if_std::AsyncWrite>::poll_close
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <S as futures_core::stream::TryStream>::try_poll_next
  12: <futures_util::stream::try_stream::ErrInto<St,E> as futures_core::stream::Stream>::poll_next
  13: <libp2p_yamux::Yamux<S> as libp2p_core::muxing::StreamMuxer>::poll_close
  14: <libp2p_core::either::EitherOutput<A,B> as libp2p_core::muxing::StreamMuxer>::poll_close
  15: <libp2p_core::muxing::Wrap<T> as libp2p_core::muxing::StreamMuxer>::poll_close
  16: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  17: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  18: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: tokio::runtime::task::core::CoreStage<T>::poll
  21: tokio::runtime::task::harness::poll_future
  22: tokio::runtime::task::harness::Harness<T,S>::poll
  23: std::thread::local::LocalKey<T>::with
  24: tokio::runtime::thread_pool::worker::Context::run_task
  25: tokio::runtime::thread_pool::worker::Context::run
  26: tokio::macros::scoped_tls::ScopedKey<T>::set
  27: tokio::runtime::thread_pool::worker::run
  28: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  29: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  30: tokio::runtime::task::harness::Harness<T,S>::poll
  31: tokio::runtime::blocking::pool::Inner::run
  32: std::sys_common::backtrace::__rust_begin_short_backtrace
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
  34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f6f9d5e73d5524b6281c10a5c89b7db35c330634/library/alloc/src/boxed.rs:1935:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f6f9d5e73d5524b6281c10a5c89b7db35c330634/library/alloc/src/boxed.rs:1935:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/f6f9d5e73d5524b6281c10a5c89b7db35c330634/library/std/src/sys/unix/thread.rs:108:17
  35: start_thread
  36: clone


Thread 'tokio-runtime-worker' panicked at 'SinkImpl::poll_flush called after error.', /home/gitlab-runner/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksink-0.1.2/src/lib.rs:225

This is a bug. Please report it at:

	https://github.com/paritytech/cumulus/issues/new
```

I reported this bug here in accordance with the last message of the log output.

**Comment by bkchr** [comment]
`cargo update -p yamux` should fix this for you.
