### ISSUE TITLE
Invalid incoming XCMP message data when XCM contains multiple assets and one of them is the relay chain asset

### ISSUE THREAD

**Issue by jiguantong** [paritytech/cumulus#1700]
version: polkadot-v0.9.26

### Steps to reproduce:
1. Rockmine submit `polkadotXcm.reserveTransferAsset` and transfer two assets, one of them is {parents: 1, Here}
```
assets: XcmVersionedMultiAssets
{
  V1: [
    {
      id: {
        Concrete: {
          parents: 0
          interior: {
            X2: [
              {
                PalletInstance: 50
              }
              {
                GeneralIndex: 9
              }
            ]
          }
        }
      }
      fun: {
        Fungible: 1,000,000,000,000
      }
    }
    {
      id: {
        Concrete: {
          parents: 1
          interior: Here
        }
      }
      fun: {
        Fungible: 1,000,000,000,000
      }
    }
  ]
}
```
encoded call: `0x1f02010101009120010001010004578647ec6e8e1ca8b91d5b6c4df991e73bcc515b2aedcef31e64db8c69e64d01080000020432052400070010a5d4e800010000070010a5d4e801000000`
 2. The dest chain can't decode the XCM and no event be deposited.

### DEBUG
I debug with local environment rococo-dev & pangolin parachain-dev & statemint-dev, the results show `xcmp-queue` can't decode the XCM here https://github.com/paritytech/cumulus/blob/polkadot-v0.9.26/pallets/xcmp-queue/src/lib.rs#L640

**Comment by bkchr** [comment]
CC @KiChjang

**Comment by KiChjang** [comment]
@jiguantong What happens if you reorder the assets, so that the `../Here` asset is first in the list?

**Comment by jiguantong** [comment]
> @jiguantong What happens if you reorder the assets, so that the `../Here` asset is first in the list?

encoded call data: `0x1f02010101009120010001010004578647ec6e8e1ca8b91d5b6c4df991e73bcc515b2aedcef31e64db8c69e64d0108000100000700e40b54020000020432052400070010a5d4e801000000`

**I can't send it after reordering.**  
### The console of chrome shows this error:
```
2022-09-28 22:54:38        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x3797d - <unknown>!rust_begin_unwind
    1: 0x3bed - <unknown>!core::panicking::panic_fmt::h18b15be283411c65
    2: 0xe6e6b - <unknown>!TaggedTransactionQueue_validate_transaction
: RuntimeApi, Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\n\n    0: 0x3797d - <unknown>!rust_begin_unwind\n    1: 0x3bed - <unknown>!core::panicking::panic_fmt::h18b15be283411c65\n
```
### My dev node log is:
```
2022-09-28 22:47:56.461 ERROR tokio-runtime-worker runtime: panicked at 'Bad input data provided to query_info: Codec error', /home/workspace/polkadot-git/cumulus/parachains/runtimes/assets/statemint/src/lib.rs:672:1
2022-09-28 22:47:57.209 ERROR tokio-runtime-worker runtime: [Parachain] panicked at 'Bad input data provided to validate_transaction: Codec error', /home/workspace/polkadot-git/cumulus/parachains/runtimes/assets/statemint/src/lib.rs:672:1
```

**Comment by KiChjang** [comment]
@jiguantong You forgot to change the `fee_asset_item` parameter to 0, Try again with that changed?

**Comment by jiguantong** [comment]
> @jiguantong You forgot to change the `fee_asset_item` parameter to 0, Try again with that changed?

`0x1f02010101009120010001010004578647ec6e8e1ca8b91d5b6c4df991e73bcc515b2aedcef31e64db8c69e64d0108000100000700e40b54020000020432052400070010a5d4e800000000`
I tried it and the error & log are the same as `fee_asset_item: 1`

**Comment by KiChjang** [comment]
Could we also ensure that it's the same amount of fungibles? Your issue description has 1 trillion units for both assets, but in your test cases, the `../Here` asset is only 10 billion.

**Comment by jiguantong** [comment]
para(2084), polkadotXcm.safeXcmVersion: 2

**Comment by jiguantong** [comment]
Well, it seems that Rockmine stopped producing blocks due to the above test

**Comment by jiguantong** [comment]
After testing it on other chains, I think this is another bug if we reorder the assets, we can track it here: https://github.com/paritytech/polkadot/issues/6074.

**Comment by JuaniRios** [comment]
@KiChjang Hello, I'm the person who created the StackExchange post.
I'm using the [xcm emulator](https://github.com/shaunxw/xcm-simulator/tree/master/xcm-emulator) and running the code in debug to inspect the variables.
I tried both orders of assets, resulting in the same XCMP Panic outcome.

I changed the source code of multiasset.rs to inspect intermediate results, and so after running:
```rust
impl Decode for MultiAssets {
	fn decode<I: codec::Input>(input: &mut I) -> Result<Self, parity_scale_codec::Error> {
		let decoded_assets = Vec::<MultiAsset>::decode(input)?;
		let assets = Self::from_sorted_and_deduplicated(decoded_assets);
		return assets.map_err(|()| "Out of order".into())
	}
}
```

decoded_assets returns a vector of 2 assets, and no matter the order defined in the sending side, the first one is always the pallet_assets one:
```rust
MultiAsset {
	id: MultiLocation { 
			parents: 1
			interior: X3(
				Parachain(1000),
				PalletInstance(50),
				GeneralIndex(1),
			)
	fun:  Fungible(500)
}
```

and the second (which is the relay token wrongly decoded):
```rust
MultiAsset {
	id: MultiLocation { 
			parents: 1
			interior: X1(
				PalletInstance(0),
			)
	fun:  Fungible(100000000000)
}
```

the assets variable returns an empty error since that's the behavior of ```Self::from_sorted_and_deduplicated```

Note:
I am using CLion's debugger to check the value of the enums. It doesn't show Multilocations in a straightforward way, because when it gets to Junctions, instead of showing me either X1, or X2, or Here, it just shows me all available options.

I can still extract the knowledge of how the enum looks like because it will fill all the junctions with correct data if it can, and then fill the rest with junk data like Parachain(0) or Junction, for example, this is how the statemint asset looks like in the debugger:

<img width="657" alt="Screenshot 2022-10-03 at 14 59 44" src="https://user-images.githubusercontent.com/54085674/193584141-ad45c732-90e8-41b8-99a6-cee6a6f57844.png">

If I were to open X8, it would also be filled at first with the same data, and then filled with junction::Junction.

I was curious what a normal reserve transfer with just one relay token would look like in the debugger, and here's what it looks like:
<img width="656" alt="Screenshot 2022-10-03 at 15 11 24" src="https://user-images.githubusercontent.com/54085674/193584818-3a828ebe-0d84-4fc0-ac32-e5c1e8ac7947.png">

So a normal relay token being sent from relay to a parachain as reserve transfer that looks like
```Multilocation { parents: 0, interior: Here }```

Is being decoded on the parachain as 
``` Multilocation { parents: 1, interior: X3(AccountId32(..), Parachain(0), AccountId32(..))}```

I cannot rule out that my findings with Clion's debugger are incorrect, but since I never had any problems getting Multilocation data this way, I am more inclined to say that it could be the decoding of relay tokens that is bugged.

**Comment by KiChjang** [comment]
So earlier, I asked what the safe XCM version is on the sender and the receiver, and they were both 2. However, when I download your code and tried to print out the actual bytes that were sent to the receiver, I get the following:

```
[0, 2, 16, 1, 8, 0, 1, 3, 0, 161, 15, 4, 50, 5, 4, 0, 209, 7, 0, 1, 0, 0, 7, 0, 232, 118, 72, 23, 10, 19, 0, 1, 0, 0, 7, 0, 232, 118, 72, 23, 1, 3, 0, 40, 107, 238, 13, 1, 0, 8, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

And this decodes to a `VersionedXcm`. Notice the first byte there? It's `0`, and that tells me that the XCM is in version 0, so somehow the sender believes that the receiver is using XCMv0, and decided to wrap the XCM in the v0 format.

I can't look into your runtime so I don't know what you have set as the safe XCM version, but it's best to use the XCM pallet's genesis config to ensure that the correct XCM version is set appropriately.

**Comment by JuaniRios** [comment]
I added the default pallet_xcm genesis config to the receiving chain (sending already had it) and now it's using ```VersionedXcm::V2``` since the first byte is 2:

<img width="2065" alt="versioned_xcm_bytes" src="https://user-images.githubusercontent.com/54085674/194869418-4365d512-7907-4d83-893f-fdc845508653.png">

I am still getting the decode error, and it's specifically coming from here:
<img width="1680" alt="Screenshot 2022-10-10 at 14 41 16" src="https://user-images.githubusercontent.com/54085674/194869584-bec89d22-ed0a-47bf-aa6d-fc77c50d1e6e.png">

**Comment by KiChjang** [comment]
@JuaniRios Next step is to take the bytes from the `data` binding, and then try to decode it using `VersionedXcm::decode(data)`. What kind of error does it return?

**Comment by JuaniRios** [comment]
I wrote 
```rust
let mut debug_data = &data[..]
let debug_decoded = VersionedXcm::<T::Call>::decode(&mut debug_data);
```
and debug_decoded ends up being Err with desc = "Could not decode `VersionedXcm::V2.0`"

**Comment by zqhxuyuan** [comment]
I can reproduce this with this testcase: https://github.com/zqhxuyuan/Acala/blob/statemine_two_asset/runtime/integration-tests/src/relaychain/statemine.rs#L260 maybe this will helpful to debug.
```
Invalid incoming XCMP message data
thread 'relaychain::statemine::statemine_reserve_transfer_ksm_and_asset_to_karura_should_not_allowed' panicked at 'Invalid incoming XCMP message data', /Users/zqh/.cargo/git/checkouts/cumulus-c031d5994ef3f0e1/803de46/pallets/xcmp-queue/src/lib.rs:678:25
```

**Comment by KiChjang** [comment]
> I can reproduce this with this testcase: https://github.com/zqhxuyuan/Acala/blob/statemine_two_asset/runtime/integration-tests/src/relaychain/statemine.rs#L260 maybe this will helpful for debug(or may not).
> 
> ```
> Invalid incoming XCMP message data
> thread 'relaychain::statemine::statemine_reserve_transfer_ksm_and_asset_to_karura_should_not_allowed' panicked at 'Invalid incoming XCMP message data', /Users/zqh/.cargo/git/checkouts/cumulus-c031d5994ef3f0e1/803de46/pallets/xcmp-queue/src/lib.rs:678:25
> ```

Your test case compiles and runs successfully when I execute it locally. My educated guess is that there are build artifacts that need to be cleaned up in your machine, particularly if you're using VSCode, as on first run, it seems to _always_ use the nightly channel to compile your project. If you later on use stable to compile your project again, you may produce weird binaries. The remedy to this is to run `cargo clean` and recompile again.

That goes for you too @JuaniRios, if the "reproducible" test case can be reproduced by another person but not me, let's try cleaning up all build artifacts and rebuild again, and see if the problem persists.

**Comment by KiChjang** [comment]
> @KiChjang I wrote
> 
> ```rust
> let mut debug_data = &data[..];
> let debug_decoded = VersionedXcm::<T::Call>::decode(&mut debug_data);
> ```
> 
> and debug_decoded ends up being Err with desc = "Could not decode `VersionedXcm::V2.0`"

Can you show us what the `cause` is? Just the `desc` is not anywhere informative enough.

**Comment by JuaniRios** [comment]
@KiChjang  It's getting really tricky to fish out the values. The cause is just a pointer to the another error struct.
I managed to get it out, and the internal error that cause points to says in its desc: "Could not decode Xcm.0".

![Screenshot 2022-10-14 at 16 20 35](https://user-images.githubusercontent.com/54085674/195870337-8ab48ff5-ac45-4851-90a5-6f242bc23a29.png)

the description is being generated by a macro, and its this one liner:
```
# [allow (deprecated )]const _ : ()= {# [automatically_derived ]impl <Call> :: parity_scale_codec :: Decode for Xcm<Call> {fn decode < __CodecInputEdqy : :: parity_scale_codec :: Input > (__codec_input_edqy : & mut __CodecInputEdqy )-> :: core :: result :: Result < Self , :: parity_scale_codec :: Error > {:: core :: result :: Result :: Ok (Xcm :: <Call> ({let __codec_res_edqy = < Vec<Instruction<Call> > as :: parity_scale_codec :: Decode > :: decode (__codec_input_edqy ); match __codec_res_edqy {:: core :: result :: Result :: Err (e )=> return :: core :: result :: Result :: Err (e . chain ("Could not decode `Xcm.0`" )), :: core :: result :: Result :: Ok (__codec_res_edqy )=> __codec_res_edqy , }}, ))}}}; 
```

Please feel free to run my code yourself and see if you get the same. Here is the link:
https://github.com/JuaniRios/xcmp-panic

You can see the error if you run the mod tests inside [/xcm-emulator/xcmp-bug/src/lib.rs](https://github.com/JuaniRios/xcmp-panic/blob/main/xcm-emulator/xcmp-bug/src/lib.rs)

note: I had to activate the "chain-error" flag of codec in the xcmp-queue pallet cargo.toml file for it to compile when adding the line ```let debug_cause = e.cause.unwrap();```

**Comment by JuaniRios** [comment]
@KiChjang any updates on this?

**Comment by SBalaguer** [comment]
Hey @JuaniRios, other teams have been able to execute multi asset XCM calls with no issues. In particular, Acala is using [this](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/xtokens), and they have not had issues with XCM. Have you looked into that?

**Comment by JuaniRios** [comment]
@SBalaguer I'm still having this issue with polkadot v0.9.38.
I haven't tried the xtokens pallet of orml because it was my understanding that pallet_assets supports xcm by default.
Am I understanding correctly that if I want to support xcm for my assets I shouldn't use pallet_assets?

**Comment by KiChjang** [comment]
IIRC this isn't a problem with XCM, but specifically the XCM simulator. A student from the PBA has tried and mentioned using actual runtimes in the simulator causes problems, but would disappear in the actual runtime code. I would look into why the XCM simulator is making weird SCALE encoding in order to resolve this.

**Comment by JuaniRios** [comment]
I'm using the [emulator](https://github.com/shaunxw/xcm-simulator), not the simulator. And @jiguantong  seemed to have that issue using real nodes.

Ill try it myself again with my own nodes and see if the error still occurs
