### ISSUE TITLE
thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9

### ISSUE THREAD

**Issue by xlc** [paritytech/cumulus#194]
When running Acala as a parachain, the collator seems building blocks but validator failed to validate it with error

`thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', `

Parachain code: https://github.com/AcalaNetwork/Acala/pull/362

Validator node 1

```
2020-08-12 00:52:48 ✨ Imported #25 (0x637d…a5e0)
2020-08-12 00:52:48 ✍️ Starting parachain attestation session (parent: 0x637d…a5e0) with active duty LocalDuty { validation: Parachain(Id(5000)), index: 0 }
thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9
2020-08-12 00:52:50 💤 Idle (2 peers), best: #25 (0x637d…a5e0), finalized #22 (0xc6f4…8949), ⬇ 424.5kiB/s ⬆ 0.8kiB/s
2020-08-12 00:52:54 ✨ Imported #26 (0x618c…5476)
2020-08-12 00:52:54 ✍️ Starting parachain attestation session (parent: 0x618c…5476) with active duty LocalDuty { validation: Relay, index: 0 }
2020-08-12 00:52:55 💤 Idle (2 peers), best: #26 (0x618c…5476), finalized #23 (0x5279…3d6d), ⬇ 0.7kiB/s ⬆ 0.9kiB/s
2020-08-12 00:53:00 🙌 Starting consensus session on top of parent 0x618cf38f3a6785bdfda6d047babb135c5f3d2e2a4f72d316aac9e0bca7925476
2020-08-12 00:53:00 🎁 Prepared block for proposing at 27 [hash: 0x1eb2337c3be0c3267543c39fedac3745e4ed5e2cc03248842a6c13d3be283bd5; parent_hash: 0x618c…5476; extrinsics (3): [0xa760…2791, 0xbebe…def1, 0xd7e1…aab4]]
2020-08-12 00:53:00 🔖 Pre-sealed block for proposal at 27. Hash now 0xfdd4ea9a883470b33fb1fb18e1f322965ece2e4fd6191d63345a2aed2cc51986, previously 0x1eb2337c3be0c3267543c39fedac3745e4ed5e2cc03248842a6c13d3be283bd5.
2020-08-12 00:53:00 ✨ Imported #27 (0xfdd4…1986)
2020-08-12 00:53:00 ✍️ Starting parachain attestation session (parent: 0xfdd4…1986) with active duty LocalDuty { validation: Relay, index: 0 }
2020-08-12 00:53:00 💤 Idle (2 peers), best: #27 (0xfdd4…1986), finalized #24 (0x43e9…de8c), ⬇ 0.6kiB/s ⬆ 0.9kiB/s
2020-08-12 00:53:05 💤 Idle (2 peers), best: #27 (0xfdd4…1986), finalized #25 (0x637d…a5e0), ⬇ 0.6kiB/s ⬆ 0.7kiB/s
2020-08-12 00:53:06 ✨ Imported #28 (0xd7ee…2fc5)
2020-08-12 00:53:06 ✍️ Starting parachain attestation session (parent: 0xd7ee…2fc5) with active duty LocalDuty { validation: Parachain(Id(5000)), index: 0 }
thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9
2020-08-12 00:53:10 💤 Idle (2 peers), best: #28 (0xd7ee…2fc5), finalized #25 (0x637d…a5e0), ⬇ 424.5kiB/s ⬆ 0.7kiB/s
2020-08-12 00:53:12 🙌 Starting consensus session on top of parent 0xd7ee0a6a26d768578b6edc374f8b0f174839f1924f2fd3c7c5dc51ff7c3c2fc5
2020-08-12 00:53:12 🎁 Prepared block for proposing at 29 [hash: 0xe4c8206d5cf1bdd4f141b504d852142cb655931f6ef51da032623702eba5313a; parent_hash: 0xd7ee…2fc5; extrinsics (3): [0x6453…d3de, 0x317e…c8e0, 0xd7e1…aab4]]
```

Collator

```
2020-08-12 00:53:12 ♻️  [Relaychain] Reorg on #29,0xfde3…e203 to #29,0xbc17…41f5, common ancestor #28,0xd7ee…2fc5
2020-08-12 00:53:12 ✨ [Relaychain] Imported #29 (0xbc17…41f5)
2020-08-12 00:53:12 🙌 Starting consensus session on top of parent 0x4e2257ea85a342d1c2601710a4afebb7fc54a2424347f043e52fa79c1070f0b7
2020-08-12 00:53:12 🎁 Prepared block for proposing at 1 [hash: 0xdd34f0dcb6792f75b1f64db7ddca5eb00e5eef185f7bd2d514cda8039e3c4db5; parent_hash: 0x4e22…f0b7; extrinsics (3): [0xe397…7823, 0xb649…b1e2, 0x57d4…b227]]
2020-08-12 00:53:12 ✨ [Parachain] Imported #1 (0xdd34…4db5)
2020-08-12 00:53:12 🎁 Prepared block for proposing at 1 [hash: 0x836823f9644662006ddda6791bc61acfd4316f2fcc484e6d69dd1cc81d664250; parent_hash: 0x4e22…f0b7; extrinsics (3): [0x8a61…981c, 0xb649…b1e2, 0x57d4…b227]]
2020-08-12 00:53:12 ✨ [Parachain] Imported #1 (0x8368…4250)
2020-08-12 00:53:13 💤 [Relaychain] Idle (2 peers), best: #29 (0xbc17…41f5), finalized #26 (0x618c…5476), ⬇ 1.0kiB/s ⬆ 848.2kiB/s
2020-08-12 00:53:15 💤 [Parachain] Idle (0 peers), best: #0 (0x4e22…f0b7), finalized #0 (0x4e22…f0b7), ⬇ 0 ⬆ 0
2020-08-12 00:53:18 ✨ [Relaychain] Imported #30 (0xe62e…d071)
2020-08-12 00:53:18 🙌 Starting consensus session on top of parent 0x4e2257ea85a342d1c2601710a4afebb7fc54a2424347f043e52fa79c1070f0b7
2020-08-12 00:53:18 🎁 Prepared block for proposing at 1 [hash: 0x71a10a9b9587374c97fa1e3eb43f6ab611a6830ec49eed9e4ab0e407ea2a55a9; parent_hash: 0x4e22…f0b7; extrinsics (3): [0x49de…1427, 0xeb85…aab7, 0x57d4…b227]]
2020-08-12 00:53:18 ✨ [Parachain] Imported #1 (0x71a1…55a9)
2020-08-12 00:53:18 💤 [Relaychain] Idle (2 peers), best: #30 (0xe62e…d071), finalized #27 (0xfdd4…1986), ⬇ 0.7kiB/s ⬆ 0.4kiB/s
2020-08-12 00:53:20 💤 [Parachain] Idle (0 peers), best: #0 (0x4e22…f0b7), finalized #0 (0x4e22…f0b7), ⬇ 0 ⬆ 0
2020-08-12 00:53:23 💤 [Relaychain] Idle (2 peers), best: #30 (0xe62e…d071), finalized #28 (0xd7ee…2fc5), ⬇ 0.5kiB/s ⬆ 424.0kiB/s
2020-08-12 00:53:24 ✨ [Relaychain] Imported #31 (0x5766…bcea)
2020-08-12 00:53:24 🙌 Starting consensus session on top of parent 0x4e2257ea85a342d1c2601710a4afebb7fc54a2424347f043e52fa79c1070f0b7
2020-08-12 00:53:24 🎁 Prepared block for proposing at 1 [hash: 0xb9ffea5ce344511cb74f2899248326e9ef068070951330ffb604e97652d492e2; parent_hash: 0x4e22…f0b7; extrinsics (3): [0x1012…7994, 0x8b2f…6ae6, 0x57d4…b227]]
2020-08-12 00:53:24 ✨ [Parachain] Imported #1 (0xb9ff…92e2)
2020-08-12 00:53:25 💤 [Parachain] Idle (0 peers), best: #0 (0x4e22…f0b7), finalized #0 (0x4e22…f0b7), ⬇ 0 ⬆ 0
2020-08-12 00:53:28 💤 [Relaychain] Idle (2 peers), best: #31 (0x5766…bcea), finalized #29 (0xbc17…41f5), ⬇ 1.1kiB/s ⬆ 424.2kiB/s
2020-08-12 00:53:30 ✨ [Relaychain] Imported #32 (0xc342…385a)
2020-08-12 00:53:30 🙌 Starting consensus session on top of parent 0x4e2257ea85a342d1c2601710a4afebb7fc54a2424347f043e52fa79c1070f0b7
2020-08-12 00:53:30 🎁 Prepared block for proposing at 1 [hash: 0x74f2c8e69123277e967f595d47447aca3391e71dbf3123b159011f39843151f2; parent_hash: 0x4e22…f0b7; extrinsics (3): [0xad97…1cfc, 0x99f3…aca3, 0x57d4…b227]]
2020-08-12 00:53:30 ✨ [Parachain] Imported #1 (0x74f2…51f2)
2020-08-12 00:53:30 💤 [Parachain] Idle (0 peers), best: #0 (0x4e22…f0b7), finalized #0 (0x4e22…f0b7), ⬇ 0 ⬆ 0
```

**Comment by xlc** [comment]
```
2020-08-12 10:59:06 ✍️ Starting parachain attestation session (parent: 0x8ee2…396b) with active duty LocalDuty { validation: Parachain(Id(5000)), index: 0 }
thread 'main' panicked at 'next_storage_key: unsupported feature for parachain validation', parachain/src/wasm_executor/mod.rs:266:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: <polkadot_parachain::wasm_executor::ValidationExternalities as sp_externalities::Externalities>::next_storage_key
   8: std::thread::local::LocalKey<T>::with
   9: sp_io::storage::next_key_version_1
  10: <<sp_io::storage::HostFunctions as sp_wasm_interface::HostFunctions>::host_functions::ExtStorageNextKeyVersion1 as sp_wasm_interface::Function>::execute
  11: <sc_executor_wasmi::FunctionExecutor as wasmi::host::Externals>::invoke_index
  12: wasmi::func::FuncInstance::invoke
  13: wasmi::func::FuncInstance::invoke
  14: <sc_executor_wasmi::WasmiInstance as sc_executor_common::wasm_runtime::WasmInstance>::call
  15: std::panicking::try
  16: std::thread::local::LocalKey<T>::with
  17: <sc_executor::native_executor::WasmExecutor as sp_core::traits::CallInWasm>::call_in_wasm
  18: polkadot_parachain::wasm_executor::validate_candidate_internal
  19: polkadot_parachain::wasm_executor::validation_host::run_worker
  20: polkadot_cli::command::run
  21: polkadot::main
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal
  24: main
```
