### ISSUE TITLE
'--relay-chain-rpc-urls' does not work via wss connection

### ISSUE THREAD

**Issue by tugytur** [paritytech/cumulus#2337]
`--relay-chain-rpc-urls` does not seem to work via a wss.

version: `polkadot-parachain_v0.9.380 0.9.380-fe24f39507f`

I first tried directly against the relay chain host which has a internal CA for wss and afterwards via the public endpoint which uses a public CA for our rpc/wss services.

These are the working flags:

```
--relay-chain-rpc-urls="ws://10.10.153.11:9944" \
--relay-chain-rpc-urls="ws://10.10.153.12:9944" \
```

I tried independently following ways to define the flag:

```
--relay-chain-rpc-urls="wss://10.10.153.12" \
--relay-chain-rpc-urls="wss://10.10.153.12:443" \
--relay-chain-rpc-urls="wss://westend.rpc.amforc.com" \
--relay-chain-rpc-urls="wss://westend.rpc.amforc.com:443" \
```

every time I get the following error:

```
polkadot-parachain[237185]: 2023-03-16 12:06:20 Is collating: no
polkadot-parachain[237185]: 2023-03-16 12:06:20 [Parachain] Trying to connect to next external relaychain node. index=0 url=Url { scheme: "wss", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(10.10.153.12)), port: None, path: "/", query: None, fragment: None }
polkadot-parachain[237185]: 2023-03-16 12:06:20 [Parachain] No valid RPC url found. Stopping RPC worker.
polkadot-parachain[237185]: 2023-03-16 12:06:20 [Parachain] Essential task `relay-chain-rpc-worker` failed. Shutting down service.
polkadot-parachain[237185]: ====================
polkadot-parachain[237185]: Version: 0.9.380-fe24f39507f
polkadot-parachain[237185]:    0: sp_panic_handler::set::{{closure}}
polkadot-parachain[237185]:    1: std::panicking::rust_panic_with_hook
polkadot-parachain[237185]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
polkadot-parachain[237185]:    2: std::panicking::begin_panic_handler::{{closure}}
polkadot-parachain[237185]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
polkadot-parachain[237185]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
polkadot-parachain[237185]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
polkadot-parachain[237185]:    4: rust_begin_unwind
polkadot-parachain[237185]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
polkadot-parachain[237185]:    5: core::panicking::panic_fmt
polkadot-parachain[237185]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
polkadot-parachain[237185]:    6: core::result::unwrap_failed
polkadot-parachain[237185]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
polkadot-parachain[237185]:    7: cumulus_relay_chain_minimal_node::new_minimal_relay_chain::{{closure}}
polkadot-parachain[237185]:    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
polkadot-parachain[237185]:    9: polkadot_parachain::service::start_node_impl::{{closure}}
polkadot-parachain[237185]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
polkadot-parachain[237185]:   11: sc_cli::runner::Runner<C>::run_node_until_exit
polkadot-parachain[237185]:   12: polkadot_parachain::command::run
polkadot-parachain[237185]:   13: polkadot_parachain::main
polkadot-parachain[237185]:   14: std::sys_common::backtrace::__rust_begin_short_backtrace
polkadot-parachain[237185]:   15: std::rt::lang_start::{{closure}}
polkadot-parachain[237185]:   16: main
polkadot-parachain[237185]:   17: __libc_start_main
polkadot-parachain[237185]:   18: _start
polkadot-parachain[237185]: Thread 'main' panicked at 'Genesis block hash is always available; qed: RpcCallError("chain_getBlockHash")', /builds/client/relay-chain-minimal-node/src/lib.rs:140
polkadot-parachain[237185]: This is a bug. Please report it at:
polkadot-parachain[237185]:         https://github.com/paritytech/cumulus/issues/new
```

I also ran tcpdump on the relay-chain host and the parachain node fails before any kind of traffic happens with the relay-chain node

**Comment by bkchr** [comment]
CC @skunert
