### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'header is last in set and contains standard change signal; must have justification;

### ISSUE THREAD

**Issue by wwwAndries** [paritytech/cumulus#2441]
Mangata backup node crashed with this error, also happened with Bifrost and Litentry node:

```
Version: 0.1.0-unknown
   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
   6: core::panicking::panic_display
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:138:5
   7: core::panicking::panic_str
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:122:5
   8: core::option::expect_failed
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/option.rs:1879:5
   9: <sc_finality_grandpa::warp_proof::NetworkProvider<Block,Backend> as sc_network_common::sync::warp::WarpSyncProvider<Block>>::generate
  10: sc_network_sync::warp_request_handler::RequestHandler<TBlock>::handle_request
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  13: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  16: tokio::runtime::task::core::Core<T,S>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  19: tokio::runtime::scheduler::multi_thread::worker::Context::run
  20: tokio::macros::scoped_tls::ScopedKey<T>::set
  21: tokio::runtime::scheduler::multi_thread::worker::run
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/thread.rs:108:17
  29: start_thread
  30: clone
Thread 'tokio-runtime-worker' panicked at 'header is last in set and contains standard change signal; must have justification; qed.', /usr/local/cargo/git/checkouts/substrate-56aa5b68bc705a80/d400e67/client/finality-grandpa/src/warp_proof.rs:132
This is a bug. Please report it at:
        https://github.com/paritytech/cumulus/issues/new
```

Version of the Mangata node is v0.28.2 instead of version 0.1.0-unknown!

Mangata Parachain Collator
✌️  version 0.1.0-unknown
❤️  by Mangata Team, 2020-2023
📋 Chain specification: Mangata Kusama Mainnet
🏷  Node name: StakeWorks | Mangata | CCN1101
👤 Role: AUTHORITY
💾 Database: RocksDb at /chains/mangata_kusama_mainnet/db/full
⛓  Native runtime: mangata-parachain-2802 (mangata-parachain-0.tx2802.au15)
Parachain id: Id(2110)

💻 Operating system: linux
💻 CPU architecture: x86_64
💻 Target environment: gnu
💻 CPU: AMD EPYC 7282 16-Core Processor
💻 CPU cores: 8
💻 Memory: 30096MB
💻 Kernel: 5.4.0-131-generic
💻 Linux distribution: Ubuntu 20.04.5 LTS
💻 Virtual machine: yes
📦 Highest known block at #17431952

LimitNOFILE=16384

ExecStart=/mangata-node \
        --chain=/mangata-kusama-mainnet.json \
        --base-path /mangata-collator/ \
        --name 'StakeWorks'  \
        --collator \
        --force-authoring \
        --execution wasm \
        --trie-cache-size 134217728 \
        --rpc-cors all \
        --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
        -- \
        --execution wasm \
        --base-path /mangata-collator/ \
        --chain kusama \
#       -sync warp \
        --state-pruning 1000 \
        --blocks-pruning 1000 \

I've synced the relaychain with "sync warp", when node was synced and switched to "sync full" after restart, I've disable "sync warp" and restarted node again. Node did run fine for over a week.

   9: <sc_finality_grandpa::warp_proof::NetworkProvider<Block,Backend> as sc_network_common::sync::warp::WarpSyncProvider<Block>>::generate
  10: **sc_network_sync::warp_request_handler::RequestHandler<TBlock>::handle_request**

**Question**: Does "sync warp" ignore pruning settings?

**Comment by altonen** [comment]
IIRC there was a recent issue about warp syncing with pruning but I can't find it any more

cc @bkchr
