### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by damianoazzolini** [paritytech/cumulus#30]
I was looking into cumulus --help using the grep command. I erroneously typed cumulus --help | grep and this happened:
```
$> ./target/release/cumulus-test-parachain-collator --help | grep
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

====================

Version: 0.1.0-e025dab-x86_64-linux-gnu

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
             at src/libcore/result.rs:1084
   6: clap::errors::Error::exit
   7: clap::app::App::get_matches_from
   8: substrate_cli::parse_and_prepare
   9: cumulus_test_parachain_collator::cli::run
  10: cumulus_test_parachain_collator::main
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
      std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  14: std::panicking::try
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start


Thread 'main' panicked at 'Error writing Error to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:1084

This is a bug. Please report it at:

        https://github.com/paritytech/cumulus/issues/new
```

**Comment by bkchr** [comment]
You don't need to open the same issue over and over again. `Cumulus` and `Polkadot` use `Substrate` and the error originates there.
