### ISSUE TITLE
Database missing expected key: 0xd6a496e2126f72816a0ae521d62073492d117d345aaea5efa9695f9a0ad40993

### ISSUE THREAD

**Issue by mikespook** [paritytech/cumulus#3030]
Hi there,

This's a report from OnFinality. In our running node, I found this error and it says I should report it. Thanks!

```
2023-08-18 05:02:36 [Parachain] delegator_share_of_total_stake     
2023-08-18 05:02:36 [Parachain] reward_for_delegator  is 0    
2023-08-18 05:02:36 [Parachain] delegator_share_of_total_stake     
2023-08-18 05:02:36 [Parachain] reward_for_delegator  is 413808520093123    
2023-08-18 05:02:36 [Parachain] delegator_share_of_total_stake     
2023-08-18 05:02:36 [Parachain] reward_for_delegator  is 42190048249537    
2023-08-18 05:02:36 [Parachain] delegator_share_of_total_stake     
2023-08-18 05:02:36 [Parachain] reward_for_delegator  is 24674998902384234    
2023-08-18 05:02:36 [Parachain] delegator_share_of_total_stake     
2023-08-18 05:02:36 [Parachain] reward_for_delegator  is 20577869833390951    
2023-08-18 05:02:36 [Parachain] ✨ Imported #1479532 (0xdc71…8fcf)    
2023-08-18 05:02:39 [Parachain] 💤 Idle (15 peers), best: #1479527 (0xfd9b…a4cb), finalized #1479020 (0xcdec…c06d), ⬇ 35.5kiB/s ⬆ 3.4kiB/s    
2023-08-18 05:02:41 [Relaychain] ⏩ Block history, #7558428 (40 peers), best: #16893952 (0x0780…a98e), finalized #16893440 (0xabab…7b4e), ⬇ 129.8kiB/s ⬆ 131.0kiB/s    
2023-08-18 05:02:44 [Parachain] 💤 Idle (15 peers), best: #1479527 (0xfd9b…a4cb), finalized #1479020 (0xcdec…c06d), ⬇ 88 B/s ⬆ 0.5kiB/s    
2023-08-18 05:02:46 [Relaychain] ⏩ Block history, #7558428 (40 peers), best: #16893956 (0xb02b…77f8), finalized #16893952 (0x0780…a98e), ⬇ 180.3kiB/s ⬆ 182.9kiB/s    

====================

Version: 0.0.1-93284378029

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/core/src/panicking.rs:64:14
   6: core::result::unwrap_failed
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/core/src/result.rs:1790:5
   7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
   8: <&mut dyn sp_externalities::Externalities as sp_io::storage::Storage>::get_version_1
   9: sp_externalities::scope_limited::with_externalities
  10: tracing::span::Span::in_scope
  11: sp_io::storage::get_version_1
  12: sp_io::storage::ExtStorageGetVersion1::call
  13: <<sp_wasm_interface::ExtendedHostFunctions<Base,Overlay> as sp_wasm_interface::HostFunctions>::register_static::Proxy<T> as sp_wasm_interface::HostFunctionRegistry>::with_function_context
  14: std::panicking::try
  15: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: wasmtime_runtime::traphandlers::catch_traps::call_closure
  21: wasmtime_setjmp
  22: wasmtime_runtime::traphandlers::catch_traps
  23: wasmtime::func::invoke_wasm_and_catch_traps
  24: wasmtime::func::typed::TypedFunc<Params,Results>::call
  25: sc_executor_wasmtime::instance_wrapper::EntryPoint::call
  26: sc_executor_wasmtime::runtime::perform_call
  27: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  28: sc_executor_common::wasm_runtime::WasmInstance::call_export
  29: std::thread::local::LocalKey<T>::with
  30: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  31: sc_executor::wasm_runtime::RuntimeCache::with_instance
  32: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  33: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  34: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  35: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
  36: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  37: sp_authority_discovery::AuthorityDiscoveryApi::authorities
  38: <T as sc_authority_discovery::worker::AuthorityDiscovery<Block>>::authorities::{{closure}}
  39: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::run::{{closure}}
  40: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  41: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  42: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  43: tokio::runtime::task::core::Core<T,S>::poll
  44: tokio::runtime::task::harness::Harness<T,S>::poll
  45: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  46: tokio::runtime::scheduler::multi_thread::worker::Context::run
  47: tokio::macros::scoped_tls::ScopedKey<T>::set
  48: tokio::runtime::scheduler::multi_thread::worker::run
  49: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  50: tokio::runtime::task::core::Core<T,S>::poll
  51: tokio::runtime::task::harness::Harness<T,S>::poll
  52: tokio::runtime::blocking::pool::Inner::run
  53: std::sys_common::backtrace::__rust_begin_short_backtrace
  54: core::ops::function::FnOnce::call_once{{vtable.shim}}
  55: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/alloc/src/boxed.rs:2000:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/alloc/src/boxed.rs:2000:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/8dfb3395411555e93399671d0c41a4ac9ed62b95/library/std/src/sys/unix/thread.rs:108:17
  56: start_thread
  57: clone


Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xd6a496e2126f72816a0ae521d62073492d117d345aaea5efa9695f9a0ad40993"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/2dff067/primitives/state-machine/src/ext.rs:189

This is a bug. Please report it at:

    https://github.com/paritytech/cumulus/issues/new
```

**Comment by liamaharon** [comment]
Was this a one-off error or something reoccurring or that you're able to reproduce?

**Comment by arkpar** [comment]
Also, what CLI settings were used here?

**Comment by mikespook** [comment]
Sorry for the late reply. I think this issue can be closed. 
It's just a one-off error and we couldn't reproduce it after a reboot.

It's from bitgreen node, the running params as following
```
--base-path=/chain-data 
--pruning=archive
--chain=/chain-data/bitgreen-polkadot-2048-raw.json
--
--no-telemetry
```

I will open another issue if the error occurred and we can reproduce it.

Thanks all! Cheers
