### ISSUE TITLE
existence of block with number new_canonical implies existence of blocks with all numbers before it 

### ISSUE THREAD

**Issue by jasl** [paritytech/cumulus#534]
The same situation with <https://github.com/PureStake/moonbeam/issues/541>, our code base are based latest master branch of Cumulus and Polkadot 0.9.8

![image](https://user-images.githubusercontent.com/1024162/125608640-0a134075-4b72-439a-a618-a9aa85c600dd.png)

This both occured on Whala (Phala@Westend) and Khala (Phala@Kusama), and only affects collator node, all collators keep crashing which means the whole parachain will stuck.

The consequence is critical but can be fix with a simple action: delete parachain db and let it re-sync

**Comment by jasl** [comment]
This error occur again, but I forgot to enable verbose to get more logs


```
2021-07-15 04:43:09 [Relaychain] ✨ Imported #8349883 (0x9130…201b)
2021-07-15 04:43:09 [Parachain] Starting collation. relay_parent=0x9130fcd6e70c3bb63f67c94057029dfa811ab171e516a67b1f689b9af065201b at=0xdcf1a7b9ba8928a9c7c213f7a7b964113b962eaff1b26c9360aa4c425b61f7a3
2021-07-15 04:43:09 [Relaychain] 💤 Idle (40 peers), best: #8349883 (0x9130…201b), finalized #8349880 (0xda87…f610), ⬇ 1.5MiB/s ⬆ 583.4kiB/s
2021-07-15 04:43:10 [Parachain] 💤 Idle (10 peers), best: #10001 (0xdcf1…f7a3), finalized #10001 (0xdcf1…f7a3), ⬇ 3.5kiB/s ⬆ 366.6kiB/s
2021-07-15 04:43:14 [Relaychain] 💤 Idle (38 peers), best: #8349883 (0x9130…201b), finalized #8349881 (0x9c21…91c9), ⬇ 1.3MiB/s ⬆ 848.7kiB/s
2021-07-15 04:43:15 [Parachain] 💤 Idle (8 peers), best: #10001 (0xdcf1…f7a3), finalized #10001 (0xdcf1…f7a3), ⬇ 0.8kiB/s ⬆ 213.5kiB/s
2021-07-15 04:43:18 [Relaychain] ✨ Imported #8349884 (0xfb91…5036)
2021-07-15 04:43:18 [Parachain] Starting collation. relay_parent=0xfb919b62f0e695509fb49dd463b809717affc434e677edbb47a7854768bc5036 at=0xdcf1a7b9ba8928a9c7c213f7a7b964113b962eaff1b26c9360aa4c425b61f7a3
2021-07-15 04:43:18 [Parachain] 🙌 Starting consensus session on top of parent 0xdcf1a7b9ba8928a9c7c213f7a7b964113b962eaff1b26c9360aa4c425b61f7a3
2021-07-15 04:43:18 [Parachain] 🎁 Prepared block for proposing at 10002 [hash: 0x2837bce3fe24fb15b9946a20023727f84f18c0559cadfbe126fe8ca7e9aad551; parent_hash: 0xdcf1…f7a3; extrinsics (2): [0x5a71…1b7e, 0xa76b…8983]]
2021-07-15 04:43:18 [Parachain] 🔖 Pre-sealed block for proposal at 10002. Hash now 0xaf829f21ee90a5d051aee4c0ba67bf0943b6c181fac6761c9d22cb009c99f9d4, previously 0x2837bce3fe24fb15b9946a20023727f84f18c0559cadfbe126fe8ca7e9aad551.
====================
Version: 0.0.3-01f46dc-x86_64-linux-gnu
   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/panicking.rs:92:14
   6: core::option::expect_failed
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/option.rs:1241:5
   7: sc_client_db::Backend<Block>::try_commit_operation
   8: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
   9: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::backend::LockImportRun<Block,B>>::lock_import_and_run::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: sc_consensus_slots::SimpleSlotWorker::on_slot::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  22: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  25: tokio::runtime::task::core::Core<T,S>::poll
  26: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
  27: tokio::runtime::task::harness::Harness<T,S>::poll
  28: std::thread::local::LocalKey<T>::with
  29: tokio::runtime::thread_pool::worker::Context::run_task
  30: tokio::runtime::thread_pool::worker::Context::run
  31: tokio::macros::scoped_tls::ScopedKey<T>::set
  32: tokio::runtime::thread_pool::worker::run
  33: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  35: tokio::runtime::task::harness::Harness<T,S>::poll
  36: tokio::runtime::blocking::pool::Inner::run
  37: tokio::runtime::context::enter
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
  40: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/alloc/src/boxed.rs:1575:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/alloc/src/boxed.rs:1575:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys/unix/thread.rs:71:17
  41: start_thread
  42: clone
Thread 'tokio-runtime-worker' panicked at 'existence of block with number `new_canonical` implies existence of blocks with all numbers before it; qed', /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/4e75f51/client/db/src/lib.rs:1309
This is a bug. Please report it at:
        https://github.com/Phala-Network/khala-parachain/issues/new
```

**Comment by h4x3rotab** [comment]
Temporary walkaround: delete the parachain db and sync the block history again

**Comment by shawntabrizi** [comment]
More discussion about this here: https://github.com/PureStake/moonbeam/issues/541

**Comment by xlc** [comment]
Our collator using v0.9.8 is having this issue, works fine when using v0.9.7
