### ISSUE TITLE
Problem with the benchmark of pallet-collator-selection

### ISSUE THREAD

**Issue by andor0** [paritytech/cumulus#588]
Tried to run the bechmark of pallet-collator-selection and got errors:
```
$ ./scripts/benchmarks.sh 
2021-08-25 09:35:21 assembling new collators for new session 0 at #0    
2021-08-25 09:35:21 assembling new collators for new session 1 at #0    
2021-08-25 09:35:22 panicked at 'called `Result::unwrap()` on an `Err` value: <wasm:stripped>', /home/ubuntu/cumulus/pallets/collator-selection/src/benchmarking.rs:59:86    
Error: Input("Error executing runtime benchmark: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x2285 - <unknown>!rust_begin_unwind\\n    1: 0x1fd5 - <unknown>!core::panicking::panic_fmt::hec165b0930ecb32e\\n    2: 0x1d03 - <unknown>!core::result::unwrap_failed::h07848c9b2569f830\\n    3: 0x10045f - <unknown>!pallet_collator_selection::benchmarking::register_candidates::h9d51b5475410d514\\n    4: 0xfe704 - <unknown>!pallet_collator_selection::benchmarking::<impl frame_benchmarking::utils::Benchmarking<frame_benchmarking::utils::BenchmarkResults> for pallet_collator_selection::pallet::Pallet<T>>::run_benchmark::{{closure}}::h59fbbbd2dc95935d\\n    5: 0xfddee - <unknown>!pallet_collator_selection::benchmarking::<impl frame_benchmarking::utils::Benchmarking<frame_benchmarking::utils::BenchmarkResults> for pallet_collator_selection::pallet::Pallet<T>>::run_benchmark::h7f1ed2b1fc1e91af\\n    6: 0x14f162 - <unknown>!<statemine_runtime::Runtime as frame_benchmarking::utils::runtime_decl_for_Benchmark::Benchmark<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,statemine_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<statemine_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<statemine_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<statemine_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<statemine_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<statemine_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<statemine_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<statemine_runtime::Runtime>)>>>>::dispatch_benchmark::h640eab193f565003\\n    7: 0x14ac76 - <unknown>!Benchmark_dispatch_benchmark\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")
2021-08-25 09:35:22 assembling new collators for new session 0 at #0    
2021-08-25 09:35:22 assembling new collators for new session 1 at #0    
2021-08-25 09:35:23 panicked at 'called `Result::unwrap()` on an `Err` value: <wasm:stripped>', /home/ubuntu/cumulus/pallets/collator-selection/src/benchmarking.rs:59:86    
Error: Input("Error executing runtime benchmark: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x21f1 - <unknown>!rust_begin_unwind\\n    1: 0x1f41 - <unknown>!core::panicking::panic_fmt::hec165b0930ecb32e\\n    2: 0x1c6f - <unknown>!core::result::unwrap_failed::h07848c9b2569f830\\n    3: 0xbb97b - <unknown>!pallet_collator_selection::benchmarking::register_candidates::h0dbfcd3d655200d0\\n    4: 0xb9bdc - <unknown>!pallet_collator_selection::benchmarking::<impl frame_benchmarking::utils::Benchmarking<frame_benchmarking::utils::BenchmarkResults> for pallet_collator_selection::pallet::Pallet<T>>::run_benchmark::{{closure}}::h07f8d44b292cae59\\n    5: 0xb92c4 - <unknown>!pallet_collator_selection::benchmarking::<impl frame_benchmarking::utils::Benchmarking<frame_benchmarking::utils::BenchmarkResults> for pallet_collator_selection::pallet::Pallet<T>>::run_benchmark::h9810c7c79fd38b39\\n    6: 0x12d453 - <unknown>!<statemint_runtime::Runtime as frame_benchmarking::utils::runtime_decl_for_Benchmark::Benchmark<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,statemint_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<statemint_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<statemint_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<statemint_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<statemint_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<statemint_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<statemint_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<statemint_runtime::Runtime>)>>>>::dispatch_benchmark::h9c3984d064bf9f19\\n    7: 0x1295ca - <unknown>!Benchmark_dispatch_benchmark\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")
```

```
$ git rev-parse HEAD
ed6ba5dfb2c112c29505e856e8971da3420ce6d0
```

**Comment by bkchr** [comment]
CC @riusricardo
