### ISSUE TITLE
Issue starting two collators at the same time

### ISSUE THREAD

**Issue by samelamin** [paritytech/cumulus#596]
Looks like the upgrade to tokio has broken running two collators

Polkadot-launch fails if running two parachains

```
in-collator helamin$ ./target/release/kylin-collator --unsafe-ws-external --rpc-cors all --rpc-external --rpc-methods Unsafe -d /tmp/kylin/parachain/alice --collator --alice  --force-authoring --ws-port 9942 --port 30333  --rpc-port 9933 --parachain-id 2013 --execution Native   -- --port 30334  --wasm-execution Compiled --chain ../polkadot/rococo-local.json 
2021-08-31 23:01:41 It isn't safe to expose RPC publicly without a proxy server that filters available set of RPC methods.    
2021-08-31 23:01:41 It isn't safe to expose RPC publicly without a proxy server that filters available set of RPC methods.    
2021-08-31 23:01:41 Kylin collator    
2021-08-31 23:01:41 ✌️  version 2.0.0-1176440-x86_64-macos    
2021-08-31 23:01:41 ❤️  by Kylin <https://github.com/kylin-network>, 2017-2021    
2021-08-31 23:01:41 📋 Chain specification: kylin rococo-local testnet    
2021-08-31 23:01:41 🏷 Node name: Alice    
2021-08-31 23:01:41 👤 Role: AUTHORITY    
2021-08-31 23:01:41 💾 Database: RocksDb at /tmp/kylin/parachain/alice/chains/kylin-rococo-local-testnet/db    
2021-08-31 23:01:41 ⛓  Native runtime: kylin-test-parachain-1 (kylin-test-parachain-1.tx1.au1)    
2021-08-31 23:01:43 Parachain id: Id(2013)    
2021-08-31 23:01:43 Parachain Account: 5Ec4AhPXYUNLCp3QNT7e6bKwKz9Xx2Svdgi7egBLzMwoXqcD    
2021-08-31 23:01:43 Parachain genesis state: 0x000000000000000000000000000000000000000000000000000000000000000000bd10b4368f711a0f3900312844d324d2b9524659594aef216b72fb3e0f9e22f003170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400    
2021-08-31 23:01:43 Is collating: yes    
2021-08-31 23:01:43 [Parachain] 🔨 Initializing Genesis block/state (state: 0xbd10…22f0, header-hash: 0x61ad…4337)    
2021-08-31 23:01:44 [Parachain] ⏱  Loaded block-time = 6s from block 0x61ad8f473f78f43beb7535008e63fbfd4e72c0241605db7e99027649d1894337    
^C
(dev) ldcl139108m:kylin-collator helamin$ 
(dev) ldcl139108m:kylin-collator helamin$ 
(dev) ldcl139108m:kylin-collator helamin$ ./target/release/kylin-collator --unsafe-ws-external --rpc-cors all --rpc-external --rpc-methods Unsafe -d /tmp/kylin/parachain/alice --collator --alice  --force-authoring --ws-port 9942 --port 30333  --rpc-port 9933 --parachain-id 2000 --execution Native   -- --port 30334  --wasm-execution Compiled --chain ../polkadot/rococo-local.json 
2021-08-31 23:01:55 It isn't safe to expose RPC publicly without a proxy server that filters available set of RPC methods.    
2021-08-31 23:01:55 It isn't safe to expose RPC publicly without a proxy server that filters available set of RPC methods.    
2021-08-31 23:01:55 Kylin collator    
2021-08-31 23:01:55 ✌️  version 2.0.0-1176440-x86_64-macos    
2021-08-31 23:01:55 ❤️  by Kylin <https://github.com/kylin-network>, 2017-2021    
2021-08-31 23:01:55 📋 Chain specification: kylin rococo-local testnet    
2021-08-31 23:01:55 🏷 Node name: Alice    
2021-08-31 23:01:55 👤 Role: AUTHORITY    
2021-08-31 23:01:55 💾 Database: RocksDb at /tmp/kylin/parachain/alice/chains/kylin-rococo-local-testnet/db    
2021-08-31 23:01:55 ⛓  Native runtime: kylin-test-parachain-1 (kylin-test-parachain-1.tx1.au1)    
2021-08-31 23:01:57 Parachain id: Id(2000)    
2021-08-31 23:01:57 Parachain Account: 5Ec4AhPUwPeyTFyuhGuBbD224mY85LKLMSqSSo33JYWCazU4    
2021-08-31 23:01:57 Parachain genesis state: 0x000000000000000000000000000000000000000000000000000000000000000000202d6208973a45a036982a1983783a02944e4ecac2d4796a48e40704beb3790803170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400    
2021-08-31 23:01:57 Is collating: yes    
2021-08-31 23:01:58 [Relaychain] 🔨 Initializing Genesis block/state (state: 0xc571…3bdb, header-hash: 0xbf85…d6a7)    
2021-08-31 23:01:58 [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2021-08-31 23:02:00 [Relaychain] ⏱  Loaded block-time = 6s from block 0xbf85d42f06d7638fde40324f848d32b16aae84183f4fa29e981714c43334d6a7    
2021-08-31 23:02:00 [Relaychain] 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2021-08-31 23:02:00 [Relaychain] 🏷 Local node identity is: 12D3KooWEema4vFPDATFRqEGHjRcSpjBhorCGb115XvgfhaabYmK    
2021-08-31 23:02:00 [Relaychain] Can't listen on /ip6/::/tcp/30334/ws because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(A(Transport(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))))))) })    
2021-08-31 23:02:00 [Relaychain] Can't listen on /ip4/0.0.0.0/tcp/30334/ws because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(A(Transport(Os { code: 48, kind: AddrInUse, message: "Address already in use" })))))))) })    
2021-08-31 23:02:00 [Relaychain] 📦 Highest known block at #0    
2021-08-31 23:02:00 [Relaychain] Unable to listen on 127.0.0.1:9945    

====================

Version: 2.0.0-1176440-x86_64-macos

   0: backtrace::backtrace::libunwind::trace
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/backtrace/libunwind.rs:90:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/backtrace/mod.rs:53:14
   1: backtrace::capture::Backtrace::create
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/capture.rs:176:9
      backtrace::capture::Backtrace::new
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.55/src/capture.rs:140:22
   2: sp_panic_handler::panic_hook
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/primitives/panic-handler/src/lib.rs:145:18
      sp_panic_handler::set::{{closure}}
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/primitives/panic-handler/src/lib.rs:61:12
   3: std::panicking::rust_panic_with_hook
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
   4: std::panicking::begin_panic::{{closure}}
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
   6: std::panicking::begin_panic
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   7: tokio::runtime::blocking::shutdown::Receiver::wait
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/blocking/shutdown.rs:51:21
   8: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/blocking/pool.rs:145:12
   9: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/blocking/pool.rs:162:9
  10: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:192:1
      core::ptr::drop_in_place<tokio::runtime::Runtime>
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:192:1
      core::ptr::drop_in_place<core::option::Option<tokio::runtime::Runtime>>
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:192:1
      core::ptr::drop_in_place<jsonrpc_server_utils::reactor::RpcEventLoop>
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:192:1
      core::ptr::drop_in_place<jsonrpc_server_utils::reactor::Executor>
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:192:1
      jsonrpc_ws_server::server::Server::start
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpc-ws-server-18.0.0/src/server.rs:127:2
  11: jsonrpc_ws_server::server_builder::ServerBuilder<M,S>::start
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpc-ws-server-18.0.0/src/server_builder.rs:138:3
      sc_rpc_server::inner::start_ws
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/client/rpc-servers/src/lib.rs:193:3
  12: sc_service::start_rpc_servers::{{closure}}
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/client/service/src/lib.rs:427:4
  13: sc_service::start_rpc_servers::maybe_start_server::{{closure}}
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/client/service/src/lib.rs:364:5
      core::option::Option<T>::map
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:487:29
      sc_service::start_rpc_servers::maybe_start_server
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/client/service/src/lib.rs:362:3
      sc_service::start_rpc_servers
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/client/service/src/lib.rs:426:3
  14: sc_service::builder::spawn_tasks
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/client/service/src/builder.rs:643:12
  15: polkadot_service::new_full
             at /Users/helamin/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/d8d5ce2/node/service/src/lib.rs:779:21
  16: polkadot_service::build_full
             at /Users/helamin/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/d8d5ce2/node/service/src/lib.rs:1356:2
      cumulus_client_service::build_polkadot_full_node
             at /Users/helamin/.cargo/git/checkouts/cumulus-59522f43471fa161/968c91e/client/service/src/lib.rs:320:31
  17: kylin_collator::service::start_node_impl::{{closure}}
             at node/src/service.rs:463:3
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
      kylin_collator::service::start_rococo_parachain_node::{{closure}}
             at node/src/service.rs:654:2
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
      kylin_collator::command::run::{{closure}}::{{closure}}
             at node/src/command.rs:355:6
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
      tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/park/thread.rs:263:54
      tokio::coop::with_budget::{{closure}}
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/coop.rs:106:9
      std::thread::local::LocalKey<T>::try_with
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
      std::thread::local::LocalKey<T>::with
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
      tokio::coop::with_budget
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/coop.rs:99:5
      tokio::coop::budget
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/coop.rs:76:5
      tokio::park::thread::CachedParkThread::block_on
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/park/thread.rs:263:31
  19: tokio::runtime::enter::Enter::block_on
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/enter.rs:151:13
      tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/thread_pool/mod.rs:71:9
      tokio::runtime::Runtime::block_on
             at /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/mod.rs:452:43
  20: sc_cli::runner::Runner<C>::run_node_until_exit
             at /Users/helamin/.cargo/git/checkouts/substrate-7e08433d4c370a21/42d3170/client/cli/src/runner.rs:162:26
      kylin_collator::command::run
             at node/src/command.rs:312:4
  21: kylin_collator::main
             at node/src/main.rs:11:2
  22: core::ops::function::FnOnce::call_once
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  23: std::rt::lang_start::{{closure}}
             at /Users/helamin/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  25: _main


Thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/helamin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/blocking/shutdown.rs:51

```

**Comment by GopherJ** [comment]
I think you need specify different ports, the log is already very clear saying this

**Comment by samelamin** [comment]
I don't think this is a port issue though? I mean it might be bit prior to 0.9.9 , it will allocate a random port?

**Comment by samelamin** [comment]
yeah the issue was with the polkadot-launch config, we now need to specify the ws-port on the validator part of the collator

Thanks :)
