### ISSUE TITLE
Fix test

### ISSUE THREAD

**Issue by bkchr** [paritytech/cumulus#617]
```
"/tmp/.tmpJJ8fKs/chains/local_testnet/db/full" removed.
"/tmp/.tmpJJ8fKs/polkadot/chains/westend2/db/full" did not exist.
test purge_chain_works ... FAILED
failures:
---- purge_chain_works stdout ----
thread 'purge_chain_works' panicked at 'assertion failed: !base_path.path().join(\"chains/local_testnet/db\").exists()', polkadot-parachains/tests/purge_chain_works.rs:74:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: core::ops::function::FnOnce::call_once
   4: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    purge_chain_works
```

**Comment by ferrell-code** [comment]
I think #613 is the reason the test fails

**Comment by bkchr** [comment]
This is not really the reason, the test works locally.
